version: '3'

services:
  jupyter_docker:
    container_name: 'jupyter_facenet'
    build: '.
#    image: jupyter-facenet:2020-08
    ports:
      - 8888:8888
    volumes:
      - $PWD/data:/data
      - $PWD/notebooks:/notebooks/local
