version: "3"
services:
  nginx:
    build: .
#    image: nginx-ubuntu_nginx:latest
#    container_name: nginx-ubuntu_nginx
    restart: always
    ports:
      - 9080:80
      - 9443:443
    volumes: 
      - ./nginx/certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
