apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-bridge.fullname" . }}
  labels:
    {{- include "nginx-bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: 443
      targetPort: {{ .Values.service.httpsPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "nginx-bridge.selectorLabels" . | nindent 4 }}
